name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven   # built-in cache for ~/.m2

      - name: Unit & integration tests
        run: ./mvnw -B verify

      # Upload surefire/failsafe reports for debugging
      - name: Test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-jdk${{ matrix.java }}
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
